kind: Deployment
apiVersion: apps/v1
metadata:
  name: msa-containerapp-java-employeeapi
  labels:
    app: msa-containerapp-java-employeeapi
    app.kubernetes.io/component: msa-containerapp-java-employeeapi
    app.kubernetes.io/instance: msa-containerapp-java-employeeapi
    app.kubernetes.io/name: msa-containerapp-java-employeeapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: msa-containerapp-java-employeeapi
  template:
    metadata:
      labels:
        app: msa-containerapp-java-employeeapi
        deploymentconfig: msa-containerapp-java-employeeapi
    spec:
      containers:
        - name: msa-containerapp-java-employeeapi
          image: >-
            image-registry.openshift-image-registry.svc:5000/cicd-demo/msa-containerapp-java-employeeapi
          imagePullPolicy: Always