kind: Deployment
apiVersion: apps/v1
metadata:
  name: empapi
  labels:
    app: employee
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employee
  template:
    metadata:
      labels:
        app: employee
    spec:
      containers:
        - name: msa-java-empapi
          image: docker.io/dainforest/msa-java-empapi:v1
