kind: Service
apiVersion: v1
metadata:
  name: msa-java-employeeapi
  labels:
    app: msa-java-employeeapi
spec:
  type: ClusterIP
  ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: msa-java-employeeapi
    deploymentconfig: msa-java-employeeapi
